---
#until condition on shell module
- hosts: webserver
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: lnxserver01
    ansible_password: "{{ ans_pwd }}"

  tasks:
  - name: running linux command
    ansible.builtin.shell: cat /etc/group
    register: output
    until: output.rc == 0
    retries: 3
     delay 2     
