---
# General playbook list iteration
- hosts: webserver
  become: yes  
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: lnxserver01
    ansible_password: "{{ ans_pwd }}"

  tasks: 
  - name: Create multiple users
    ansible_become_user:
      name: "{{ item }}" 
      group: IT_suppotrs   
      state: present
    loop:
        - webuser1
        - webuser2       